name: Runners

on:
  # We must do a trigger on a push: instead of a types: closed so GitHub Secrets
  # are available to the workflow run
  push:
    branches:
      - 'main'
#    paths:
#      - 'actions-runner-controller/runner/**'
#      - '!actions-runner-controller/runner/Makefile'
#      - 'actions-runner-controller/.github/workflows/runners.yaml'
#      - '!**.md'

env:
  DOCKERHUB_USERNAME: titilambert
  CUDA_BASE_IMAGE: nvidia/cuda:11.7.1-cudnn8-devel

jobs:
  build-runners:
    name: Build cuda-actions-runner-ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get env vars from upstream action-runner-controller
        run: |
          runner_version=$(grep -R "RUNNER_VERSION:" actions-runner-controller/.github/workflows/runners.yaml | tr -d " " | cut -d ":" -f 2)
          docker_version=$(grep -R "DOCKER_VERSION:" actions-runner-controller/.github/workflows/runners.yaml | tr -d " " | cut -d ":" -f 2)
          runner_container_hooks_version=$(grep -R "RUNNER_CONTAINER_HOOKS_VERSION:" actions-runner-controller/.github/workflows/runners.yaml | tr -d " " | cut -d ":" -f)
          echo "RUNNER_VRSION=$runner_version" >> $GITHUB_ENV
          echo "DOCKER_VERSION=$docker_version" >> $GITHUB_ENV
          echo "RUNNER_CONTAINER_HOOKS_VERSION=$runner_container_hooks_version" >> $GITHUB_ENV
      - name: Patch Dockerfile
        run: |
          sed -i "s@FROM \(ubuntu:[0-9]\{2\}\.[0-9]\{2\}\)@FROM ${CUDA_BASE_IMAGE}-\1@" actions-runner-controller/runner/actions-runner.dockerfile
          cat actions-runner-controller/runner/actions-runner.dockerfile

      - name: Setup Docker Environment
        id: vars
        uses: ./actions-runner-controller/.github/actions/setup-docker-environment
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            #ghcr_username: ${{ github.actor }}
            #ghcr_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Versioned Tags
        uses: docker/build-push-action@v3
        with:
          context: ./actions-runner-controller/runner
          file: ./actions-runner-controller/runner/actions-runner.dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
